trying to get cibuild file

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,3 +1,8 @@
-#!/bin/sh
-install: gem install jekyll html-proofer
-script: jekyll build && htmlproofer ./_site
+#!/usr/bin/env bash
+set -e # halt script on error
+
+bundle exec jekyll build
+bundle exec htmlproofer ./_site
+
+gem install jekyll html-proofer
+jekyll build && htmlproofer ./_site
